CREATE TABLE HIGHWAYS(
HIGHWAY_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
DISTANCE INT(10)
);

CREATE TABLE USERS(
USER_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL
);